# Generated by Django 5.0.4 on 2024-07-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deutschwithusapi', '0002_counselling_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
    ]
